name: Package Theme Updates

on:
  push:
    paths-ignore:
      - '*.7z'
      - '.*'
      - '*.md'
      - 'LICENSE'

jobs:
  package-themes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          
      - name: Package Modified Themes
        run: |
          # Get modified files from Themes directory
          MODIFIED_FILES=$(git show --name-only --pretty="" HEAD | grep '^Themes/' || true)
          
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No theme files were modified"
            exit 0
          fi
          
          echo "Modified files:"
          echo "$MODIFIED_FILES"
          
          # Extract unique theme names from modified files (now one level deeper)
          THEMES=$(echo "$MODIFIED_FILES" | cut -d'/' -f2 | sort -u)
          
          echo "Debug: Listing each theme individually:"
          printf '%s\n' "$THEMES"
          
          WORKSPACE="$PWD"
          
          # Process each modified theme
          printf '%s\n' "$THEMES" | while IFS= read -r theme; do
            echo "Debug: Processing theme: '$theme'"
            if [ -d "Themes/$theme" ]; then
              echo "Debug: Theme directory exists: 'Themes/$theme'"
              # Remove existing archive if it exists
              rm -f "${WORKSPACE}/${theme}.7z"
              
              # Create temporary directory structure
              mkdir -p "temp/mnt/SDCARD/Themes"
              cp -r "Themes/$theme" "temp/mnt/SDCARD/Themes/"
              
              # Create fresh 7z archive from workspace root
              7z a -r "${WORKSPACE}/${theme}.7z" "${WORKSPACE}/temp/mnt"
              
              # Cleanup
              rm -rf temp
            else
              echo "Debug: Theme directory does not exist: 'Themes/$theme'"
            fi
          done
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.7z
          git commit -m "Update theme packages" || echo "No changes to commit"
          git push
